services:
  php:
    image: php:8.1-cli
    container_name: php-container
    platform: linux/amd64
    volumes:
      - ./src:/var/www/html  # Monta el directorio src a /var/www/html en el contenedor
    working_dir: /var/www/html  # Define el directorio de trabajo dentro del contenedor
    networks:
      - app-network
    command: bash -c "composer install && tail -f /dev/null"  # Ejecuta composer install y mantiene el contenedor en ejecución

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
    ports:
      - "3308:3306"  # Exponer el puerto de MySQL
    volumes:
      - mysql-data:/var/lib/mysql  # Persistir los datos
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge